### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by galantra** [cofinley/FluentForeverVocabBuilder#2]
Hi,
where exactly do I do the following:

> Go into the project's directory
> python -m venv venv
> 
>     Python 3
> 
> venv\Scripts\activate
> 
>     Forward slashes on Linux/Mac
> 
> pip install -r requirements.txt

Sorry, I#m new to github.

**Comment by cofinley** [comment]
Once you have git and Python installed, navigate to a folder on your computer with the command line (Command Prompt for Windows, Terminal/iTerm for Mac OSX, Terminal for Linux). Then you can run these commands. You can find tutorials for these steps online.

**Comment by galantra** [comment]
Thank you! I've figured it out. I had to deal with [Errno 13]
