### ISSUE TITLE
Suggestion: target language image search

### ISSUE THREAD

**Issue by galantra** [cofinley/FluentForeverVocabBuilder#4]
I've tried "Bank", which in German means both bank and bench.
I only get images for banks. Thus, I suppose the VocabBuilder uses only the English version of google.
As [fluent forever](https://blog.fluent-forever.com/chapter4/ )report, it is much more accurate to search in your **target language's version of google**.

**Comment by cofinley** [comment]
The Google search is set to go by language:  https://github.com/cofinley/FluentForeverVocabBuilder/blob/master/app/service/images.py#L31

I’ve realized that Google is pretty loose with their searches. For example, images.google.fr will definitely recognize English searches fine and sometimes these override the French results I’m looking for. What helps is using additional target language words in your search or appending the language itself like “français” or “deutsch” to narrow things down further.

Hope this helps, thanks for the feedback!
