### ISSUE TITLE
Image search with special characters, such as diacritics

### ISSUE THREAD

**Issue by galantra** [cofinley/FluentForeverVocabBuilder#6]
Hi,  
nothing urgent. I just want to inform you:
I use your application frequently to prepare Polish cards. Polish includes some special letter like ź, ł, ą…
The image search returns no images when one of them is included. I have to change it to the base letter (z, l, a, etc.).
If I then search for "pisac" instead of "pisać", I get pictures of [Písac](https://en.wikipedia.org/wiki/P%C3%ADsac).

**Comment by cofinley** [comment]
Thanks for the feedback!

I looked into and apparently the language set in the browser was not making its way to the back-end for image searches specifically. I changed this and got what looks to be correct results:

![](https://i.imgur.com/RP7kAZ6.png)

Let me know if this works for you after pulling the latest changes.

Thank for using the application too!

**Comment by galantra** [comment]
Thank you! :)
